### PR TITLE
KUDU-3007. Support building Kudu on aarch64 platform

### PR DESCRIPTION
**Pull request by liusheng**
This change try to modify and make Kudu can build sucessfully on both
x86_64 and aarch64 platform.

Change-Id: I2953519c5d28de17e6b2bb7094abab0c1cd12c97

### CODE REVIEW

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck docker

**Comment by liusheng** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Pull request closed without merging**
